### ISSUE TITLE
A 800  Miniconda    conda3     Python  3.10(ubuntu22.04) Cuda  1

### ISSUE THREAD

**Issue by Albertchamberlain** [mayuelala/FollowYourCanvas#11]
Traceback (most recent call last):
  File "/root/autodl-tmp/FollowYourCanvas-main/inference_outpainting-dir.py", line 29, in <module>
    import diffusers
  File "/root/autodl-tmp/FollowYourCanvas-main/diffusers/__init__.py", line 28, in <module>
    from .models import (
  File "/root/autodl-tmp/FollowYourCanvas-main/diffusers/models/__init__.py", line 19, in <module>
    from .attention import Transformer2DModel
  File "/root/autodl-tmp/FollowYourCanvas-main/diffusers/models/attention.py", line 43, in <module>
    import xformers.ops
  File "/root/miniconda3/lib/python3.10/site-packages/xformers/ops/__init__.py", line 8, in <module>
    from .fmha import (
  File "/root/miniconda3/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 12, in <module>
    from . import ck, ck_decoder, ck_splitk, cutlass, decoder, flash, small_k, triton_splitk
  File "/root/miniconda3/lib/python3.10/site-packages/xformers/ops/fmha/triton_splitk.py", line 89, in <module>
    if TYPE_CHECKING or _is_triton_available():
  File "/root/miniconda3/lib/python3.10/site-packages/xformers/__init__.py", line 38, in func_wrapper
    value = func()
  File "/root/miniconda3/lib/python3.10/site-packages/xformers/__init__.py", line 54, in _is_triton_available
    if torch.cuda.get_device_capability("cuda") < (8, 0):
  File "/root/miniconda3/lib/python3.10/site-packages/torch/cuda/__init__.py", line 430, in get_device_capability
    prop = get_device_properties(device)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/cuda/__init__.py", line 444, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "/root/miniconda3/lib/python3.10/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: random_device could not be read

**Comment by Albertchamberlain** [comment]
What types of gpu you use? A800? 4090? or A100 or V100
